In [0]:
import numpy as np
import pandas as pd
import scipy as sc
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.utils import resample

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import pairwise_distances

In [0]:
#--------------------Run this cell to mount your Google Drive-------------------
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
#Reading the file from Google Drive

data = pd.read_csv("/content/drive/My Drive/ER/Recommendation System/anime.csv", sep = ',', encoding='latin-1')
#data_x = data.drop(labels = ["y"], axis = 1)
#data_y = data["y"]

In [0]:
sns.set_style(style = "whitegrid")

In [0]:
data.head()

   anime_id                              name  ... rating members
0     32281                    Kimi no Na wa.  ...   9.37  200630
1      5114  Fullmetal Alchemist: Brotherhood  ...   9.26  793665
2     28977                         GintamaÂ°  ...   9.25  114262
3      9253                       Steins;Gate  ...   9.17  673572
4      9969                     Gintama&#039;  ...   9.16  151266

[5 rows x 7 columns]

In [0]:
data.shape

(12294, 7)

In [0]:
data["genre"].head()

0                 Drama, Romance, School, Supernatural
1    Action, Adventure, Drama, Fantasy, Magic, Mili...
2    Action, Comedy, Historical, Parody, Samurai, S...
3                                     Sci-Fi, Thriller
4    Action, Comedy, Historical, Parody, Samurai, S...
Name: genre, dtype: object

In [0]:
data["genre"].isnull().sum()
#There are 62 records with null value in "genre" data.

62

In [0]:
data[(data["genre"].isnull()) == True]
#Theses are the records having null value in genre.
#Since  there are more than 12000 records, I am deleting these 62 records
#with Null values in genre.

       anime_id  ... members
2844      33242  ...    6604
3541      33589  ...   12345
6040      29765  ...     313
6646      32695  ...     242
7018      33187  ...     607
...         ...  ...     ...
11070     32032  ...    1797
11086     34310  ...      51
11097     34474  ...     843
11112     33035  ...    2294
11113     33390  ...     160

[62 rows x 7 columns]

In [0]:
data[(data["genre"].isnull()) == True].index

Int64Index([ 2844,  3541,  6040,  6646,  7018,  7198,  7335,  7349,  7426,
             7498,  7591,  7645,  7685,  7708,  7716,  7738,  7759,  7824,
             7876,  7899,  7982,  8235,  8279,  8304,  8565,  8716,  8766,
             8897,  8900,  8938,  8955,  9105,  9137,  9142,  9171,  9265,
             9413,  9559,  9903,  9978, 10153, 10243, 10424, 10575, 10719,
            10807, 10863, 10925, 10956, 10982, 10983, 10990, 10992, 11020,
            11046, 11050, 11064, 11070, 11086, 11097, 11112, 11113],
           dtype='int64')

In [0]:
#Deleting Data which has Genre as Null.
data.drop([ 2844,  3541,  6040,  6646,  7018,  7198,  7335,  7349,  7426,
             7498,  7591,  7645,  7685,  7708,  7716,  7738,  7759,  7824,
             7876,  7899,  7982,  8235,  8279,  8304,  8565,  8716,  8766,
             8897,  8900,  8938,  8955,  9105,  9137,  9142,  9171,  9265,
             9413,  9559,  9903,  9978, 10153, 10243, 10424, 10575, 10719,
            10807, 10863, 10925, 10956, 10982, 10983, 10990, 10992, 11020,
            11046, 11050, 11064, 11070, 11086, 11097, 11112, 11113], inplace = True)

In [0]:
data.shape

(12232, 7)

In [0]:
tfidf = TfidfVectorizer()
tf_mat = tfidf.fit_transform(data["genre"])

In [0]:
cosine_dissim_mat = pairwise_distances(tf_mat, tf_mat, metric = "cosine")

In [0]:
cosine_sim_mat = 1 - pd.DataFrame(cosine_dissim_mat)

In [0]:
pd.DataFrame(cosine_sim_mat)

          0         1         2         3      ...  12228  12229  12230  12231
0      1.000000  0.147783  0.000000  0.000000  ...    0.0    0.0    0.0    0.0
1      0.147783  1.000000  0.178500  0.000000  ...    0.0    0.0    0.0    0.0
2      0.000000  0.178500  1.000000  0.220705  ...    0.0    0.0    0.0    0.0
3      0.000000  0.000000  0.220705  1.000000  ...    0.0    0.0    0.0    0.0
4      0.000000  0.178500  1.000000  0.220705  ...    0.0    0.0    0.0    0.0
...         ...       ...       ...       ...  ...    ...    ...    ...    ...
12227  0.000000  0.000000  0.000000  0.000000  ...    1.0    1.0    1.0    1.0
12228  0.000000  0.000000  0.000000  0.000000  ...    1.0    1.0    1.0    1.0
12229  0.000000  0.000000  0.000000  0.000000  ...    1.0    1.0    1.0    1.0
12230  0.000000  0.000000  0.000000  0.000000  ...    1.0    1.0    1.0    1.0
12231  0.000000  0.000000  0.000000  0.000000  ...    1.0    1.0    1.0    1.0

[12232 rows x 12232 columns]

In [0]:
#Index number to Anime name
#For Converting Index number to corresponding Anime Name.

index_to_name = dict()
for row in data.iterrows():
  index_to_name[row[0]] = row[1][1]

In [0]:
#Anime name to index number
#For Converting Anime Name to corresponding Index Number.

name_to_index = dict()
for row in data.iterrows():
  name_to_index[row[1][1]] = row[0]

In [0]:
cosine_simmat_df = pd.DataFrame(cosine_sim_mat)

In [0]:
def Recommendation(index, N):
  
  #Sorting
  cos_tuple = [(k,v) for k,v in dict(cosine_simmat_df[index]).items()]
  cosine_sim_sorted = sorted(cos_tuple, key = lambda i: i[1], reverse = True)

  #TopN
  list_a = []
  for i in cosine_sim_sorted[0:N]:
      list_a.append(i[0])
        
  #Printing Recommendations
  list_name = [index_to_name[i] for i in list_a]
  print("Recommended Movie list: \n")
  print(list_name)

In [0]:
#Taking input of Movie name and 
#number of Recommendations required.
#Calling Recommendation function.

Movie = str(input("Enter the name of Anime:"))
TopN = int(input("Enter how many Recommendations you want:\n"))

Recommendation(name_to_index[Movie], TopN)

Enter the name of Anime:Fullmetal Alchemist: Brotherhood
Enter how many Recommendations you want:
10
Recommended Movie list:

['Fullmetal Alchemist: Brotherhood', 'Fullmetal Alchemist', 'Fullmetal Alchemist: The Sacred Star of Milos', 'Fullmetal Alchemist: Brotherhood Specials', 'Tales of Vesperia: The First Strike', 'Tetsujin 28-gou: Hakuchuu no Zangetsu', 'Fullmetal Alchemist: Reflections', 'Magi: The Kingdom of Magic', 'Magi: The Labyrinth of Magic', 'Magi: Sinbad no Bouken (TV)']